# Generated by Django 2.1.5 on 2019-02-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[(1, 'Read'), (2, 'Not Read')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('review_type', models.CharField(choices=[(1, 'Member'), (2, 'Online')], max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
